---
- hosts: ovirt-hosts-all
  tasks:
  - name: enable Centos-Base
    replace:
      path: /etc/yum.repos.d/CentOS-Base.repo
      regexp: 'enabled=0'
      replace: 'enabled=1'
  - name: Remove versionlock
    command: yum versionlock clear
  - name: yum update all packages 
    yum:
      name: '*'
      state: latest
  - name: NFS share packages 
    yum:
      name:
        - nfs-utils
        - portmap
        - chkconfig
      state: present 
